development:
  merchant_id: "CiguwF07531667026886"
  merchant_key: "%TwtHXKHa@faea61"
  website: WEBSTAGING
  industry_type: Retail
  channel_id: WEB
  transaction_url: https://securegw-stage.paytm.in/theia/processTransaction